"""ontoloche -- a registry of types, with a proposal->approval loop around every
addition, a lifecycle for every entry, and a mechanical answer to "if I add this, what
will silently ignore it?".

v0, unstable. Every name here may change without a deprecation path.
"""

from .adapter import (
    Capabilities,
    ConsumerRecord,
    EdgePage,
    EdgeQuery,
    EdgeRecord,
    EventRecord,
    ProposalPage,
    ProposalQuery,
    ProposalRecord,
    StorageAdapter,
    TypePage,
    TypeQuery,
    TypeRecord,
    UsageRecord,
)
from .attributes import AttributeCensus, AttributeSchema, FieldSpec
from .actions import (
    ActionFamily,
    Effect,
    EdgeRef,
    InputSpec,
    Invocation,
    InvocationProvenance,
    InvocationReport,
    Precondition,
    PreconditionResult,
    Preflight,
    ProjectionReport,
    action_attributes,
)
from .edges import (
    Edge,
    EdgeFamily,
    EdgeProvenance,
    InstanceRef,
    NeighborEdge,
    NeighborReport,
    NodeRef,
    TypeRef,
)
from .errors import (
    AlreadyExists,
    AmbiguousKind,
    NotSupported,
    SchemaMismatch,
    StoreVersionUnknown,
    UnknownType,
)
from .policy import NamespacePolicy, TierOrder
from .registry import Registry
from .types import (
    Citation,
    Consumer,
    ConsumerReport,
    Evidence,
    MergeResult,
    NotAType,
    PredicateEntry,
    PredicateListing,
    Proposal,
    Provenance,
    ProvenanceEvent,
    Refusal,
    Rejection,
    Resolution,
    ResolveContext,
    TypeEntry,
    TypeListing,
    UsageReport,
)

__all__ = [
    # ACTIONS.md v0's shapes, row 6b. Exported for the reason EDGES.md's are: a host
    # that has to BUILD a family should not have to know which private module it lives
    # in. Row 6b's first adversarial round found `from ontoloche import Effect`
    # raising ImportError while every EDGES shape was re-exported.
    "ActionFamily",
    "Effect",
    "EdgeRef",
    "InputSpec",
    "Invocation",
    "InvocationProvenance",
    "InvocationReport",
    "Precondition",
    "PreconditionResult",
    "Preflight",
    "ProjectionReport",
    "action_attributes",
    "Registry",
    "Citation",
    "Consumer",
    "ConsumerReport",
    "Evidence",
    "MergeResult",
    "NotAType",
    "PredicateEntry",
    "PredicateListing",
    "Proposal",
    "Provenance",
    "ProvenanceEvent",
    "Refusal",
    "Rejection",
    "Resolution",
    "ResolveContext",
    "TypeEntry",
    "TypeListing",
    "UsageReport",
    "AttributeCensus",
    "AttributeSchema",
    "FieldSpec",
    "NamespacePolicy",
    "TierOrder",
    "Capabilities",
    "StorageAdapter",
    "TypeRecord",
    "ProposalRecord",
    "ConsumerRecord",
    "UsageRecord",
    "EventRecord",
    "TypeQuery",
    "TypePage",
    "ProposalQuery",
    "ProposalPage",
    "EdgeRecord",
    "EdgeQuery",
    "EdgePage",
    "Edge",
    "EdgeFamily",
    "EdgeProvenance",
    "InstanceRef",
    "NeighborEdge",
    "NeighborReport",
    "NodeRef",
    "TypeRef",
    "AlreadyExists",
    "AmbiguousKind",
    "NotSupported",
    "SchemaMismatch",
    "StoreVersionUnknown",
    "UnknownType",
]
